export type SectionId =
  | 'summary'
  | 'contact'
  | 'experience'
  | 'education'
  | 'skills'
  | 'awards'
  | 'publications'
  | 'certifications'
  | 'professionalAffiliations'
  | 'volunteerWork'
  | 'hobbiesAndInterests'
  | 'languages'
  | 'testimonials'
